---
services:
  template-api:
    container_name: template-api
    restart: always
    build:
      dockerfile: Dockerfile
    image: template-api:latest
    environment:
      PROFILE: local
    ports:
      - "8080:8080"
