---

server:
  port: 8080

springtools:
  jwt-secret: world
  access-token: world

spring:
  application:
    name: template-api

springdoc:
  api-docs:
    path: /api-docs.yml
  swagger-ui:
    path: /docs
