---
server:
  port: 8080

springtools:
  jwt-secret: world
  access-token: world

springdoc:
  api-docs:
    path: /api-docs.yml
  swagger-ui:
    path: /docs

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /
      path-mapping:
        prometheus: /metrics
