---

name: Sync develop with master

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create a new branch
        run: |
          git checkout -b backport

      - name: Push the new branch
        run: |
          git push origin backport

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "backport"
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Sync develop with master"
          pr_body: "Update develop with the latest changes from master."
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate branch name
        run: |
          branch_name="${{ github.head_ref }}"
          target_branch_name="${{ github.base_ref }}"
          echo "branch: $branch_name to target branch: $target_branch_name"

          release_pattern="^(release)/[0-9]+.[0-9]+.[0-9]+$"
          hotfix_pattern="^(hotfix)/[0-9]+.[0-9]+.[0-9]+$"
          feature_pattern="^(feature)/([a-zA-Z0-9-]+)$"

          if [[ "$branch_name" =~ $feature_pattern ]]; then
            echo "Feature branch detected"
            if [[ "$target_branch_name" != "develop" ]]; then
              echo "Feature branch must target develop"
              exit 1
            fi
          elif [[ "$branch_name" =~ $release_pattern ]]; then
            echo "Release branch detected"
            if [[ "$target_branch_name" != "master" ]]; then
              echo "Release branch must target master"
              exit 1
            fi
          elif [[ "$branch_name" =~ $hotfix_pattern ]]; then
            echo "Hotfix branch detected"
            if [[ "$target_branch_name" != "master" ]]; then
              echo "Hotfix branch must target master"
              exit 1
            fi
          elif [[ "$branch_name" =~ "backport" ]]; then
            echo "Backport detected"
          else
            echo "Invalid branch name"
            exit 1
          fi
        shell: bash
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate open api spec
        run: ./gradlew openApiGenerate
      - name: Run unit and component tests
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: ./gradlew test
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate open api spec
        run: ./gradlew openApiGenerate
      - name: Run build
        run: ./gradlew build
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
