---

on: [pull_request]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          pattern="^(feature|release|hotfix)/[a-z0-9-]+$"
          if [[ ! $branch_name =~ $pattern ]]; then
            echo "ERROR: The name of the branch is not in the correct format!"
            echo -e "Branch names should have a prefix
          (feature/, release/, hotfix/) and should be in kebab-case."
            echo "Example: feature/create-endpoint"
            exit 1
          fi
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate open api spec
        run: ./gradlew openApiGenerate
      - name: Run unit and component tests
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: ./gradlew test
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate open api spec
        run: ./gradlew openApiGenerate
      - name: Run build
        run: ./gradlew build
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
